# Generated by Django 6.0.1 on 2026-08-16 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_meta_follow_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Meta',
        ),
        migrations.AlterUniqueTogether(
            name='follow',
            unique_together={('follower', 'following')},
        ),
    ]
